/*
* Copyright (c) 2024 Contributors to the Eclipse Foundation.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
*
* Contributors:
*   SmartCity Jena - initial
*   Stefan Bischof (bipolis.org) - initial
*/
package org.eclipse.daanse.jdbc.datasource.metatype.mssqlserver.api.ocd;

import org.eclipse.daanse.jdbc.datasource.metatype.mssqlserver.api.Constants;
import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.AttributeType;
import org.osgi.service.metatype.annotations.Option;

public interface BaseConfig {

    String OCD_LOCALIZATION = "OSGI-INF/l10n/org.eclipse.daanse.jdbc.datasource.metatype.mssqlserver.ocd";
    String L10N_PREFIX = "%";

    String L10N_POSTFIX_DESCRIPTION = ".description";
    String L10N_POSTFIX_NAME = ".name";
    String L10N_POSTFIX_OPTION = ".option";
    String L10N_POSTFIX_LABEL = ".label";

    String L10N_PASSWORD_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PASSWORD + L10N_POSTFIX_NAME;
    String L10N_PASSWORD_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PASSWORD + L10N_POSTFIX_DESCRIPTION;

    String L10N_PORTNUMBER_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PORTNUMBER + L10N_POSTFIX_NAME;
    String L10N_PORT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PORTNUMBER + L10N_POSTFIX_DESCRIPTION;

    String L10N_SERVERNAME_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SERVERNAME + L10N_POSTFIX_NAME;
    String L10N_SERVERNAME_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SERVERNAME
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_INSTANCENAME_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_INSTANCENAME + L10N_POSTFIX_NAME;
    String L10N_INSTANCENAME_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_INSTANCENAME
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_APPLICATIONNAME_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_APPLICATIONNAME + L10N_POSTFIX_NAME;
    String L10N_APPLICATIONNAME_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_APPLICATIONNAME
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_USER_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USER + L10N_POSTFIX_NAME;
    String L10N_USER_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USER + L10N_POSTFIX_DESCRIPTION;

    String L10N_DATABASENAME_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DATABASENAME + L10N_POSTFIX_NAME;
    String L10N_DATABASENAME_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DATABASENAME
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_ENCRYPT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ENCRYPT + L10N_POSTFIX_NAME;
    String L10N_ENCRYPT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ENCRYPT + L10N_POSTFIX_DESCRIPTION;

    String L10N_TRUST_SERVER_CERTIFICATE_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_TRUST_SERVER_CERTIFICATE
            + L10N_POSTFIX_NAME;
    String L10N_TRUST_SERVER_CERTIFICATE_DESCRIPTION = L10N_PREFIX
            + Constants.DATASOURCE_PROPERTY_TRUST_SERVER_CERTIFICATE + L10N_POSTFIX_DESCRIPTION;

    String L10N_INTEGRATED_SECURITY_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_INTEGRATED_SECURITY
            + L10N_POSTFIX_NAME;
    String L10N_INTEGRATED_SECURITY_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_INTEGRATED_SECURITY
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_AUTHENTICATION_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_AUTHENTICATION + L10N_POSTFIX_NAME;
    String L10N_AUTHENTICATION_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_AUTHENTICATION
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_LOGIN_TIMEOUT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_LOGIN_TIMEOUT + L10N_POSTFIX_NAME;
    String L10N_LOGIN_TIMEOUT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_LOGIN_TIMEOUT
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_QUERY_TIMEOUT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_QUERY_TIMEOUT + L10N_POSTFIX_NAME;
    String L10N_QUERY_TIMEOUT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_QUERY_TIMEOUT
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_SOCKET_TIMEOUT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SOCKET_TIMEOUT + L10N_POSTFIX_NAME;
    String L10N_SOCKET_TIMEOUT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SOCKET_TIMEOUT
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_RESPONSE_BUFFERING_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_RESPONSE_BUFFERING
            + L10N_POSTFIX_NAME;
    String L10N_RESPONSE_BUFFERING_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_RESPONSE_BUFFERING
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_SELECT_METHOD_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SELECT_METHOD + L10N_POSTFIX_NAME;
    String L10N_SELECT_METHOD_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SELECT_METHOD
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_APPLICATION_INTENT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_APPLICATION_INTENT
            + L10N_POSTFIX_NAME;
    String L10N_APPLICATION_INTENT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_APPLICATION_INTENT
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_MULTI_SUBNET_FAILOVER_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_MULTI_SUBNET_FAILOVER
            + L10N_POSTFIX_NAME;
    String L10N_MULTI_SUBNET_FAILOVER_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_MULTI_SUBNET_FAILOVER
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_FAILOVER_PARTNER_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_FAILOVER_PARTNER
            + L10N_POSTFIX_NAME;
    String L10N_FAILOVER_PARTNER_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_FAILOVER_PARTNER
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_PACKET_SIZE_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PACKET_SIZE + L10N_POSTFIX_NAME;
    String L10N_PACKET_SIZE_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PACKET_SIZE
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_LOCK_TIMEOUT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_LOCK_TIMEOUT + L10N_POSTFIX_NAME;
    String L10N_LOCK_TIMEOUT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_LOCK_TIMEOUT
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_COLUMN_ENCRYPTION_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_COLUMN_ENCRYPTION
            + L10N_POSTFIX_NAME;
    String L10N_COLUMN_ENCRYPTION_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_COLUMN_ENCRYPTION
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_SEND_STRING_PARAMETERS_AS_UNICODE_NAME = L10N_PREFIX
            + Constants.DATASOURCE_PROPERTY_SEND_STRING_PARAMETERS_AS_UNICODE + L10N_POSTFIX_NAME;
    String L10N_SEND_STRING_PARAMETERS_AS_UNICODE_DESCRIPTION = L10N_PREFIX
            + Constants.DATASOURCE_PROPERTY_SEND_STRING_PARAMETERS_AS_UNICODE + L10N_POSTFIX_DESCRIPTION;

    // Option label constants for Encrypt
    String L10N_ENCRYPT_OPTION_TRUE_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ENCRYPT + L10N_POSTFIX_OPTION + ".true" + L10N_POSTFIX_LABEL;
    String L10N_ENCRYPT_OPTION_FALSE_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ENCRYPT + L10N_POSTFIX_OPTION + ".false" + L10N_POSTFIX_LABEL;
    String L10N_ENCRYPT_OPTION_STRICT_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ENCRYPT + L10N_POSTFIX_OPTION + ".strict" + L10N_POSTFIX_LABEL;

    // Option label constants for Authentication
    String L10N_AUTHENTICATION_OPTION_NOT_SPECIFIED_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_AUTHENTICATION + L10N_POSTFIX_OPTION + ".NotSpecified" + L10N_POSTFIX_LABEL;
    String L10N_AUTHENTICATION_OPTION_SQL_PASSWORD_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_AUTHENTICATION + L10N_POSTFIX_OPTION + ".SqlPassword" + L10N_POSTFIX_LABEL;
    String L10N_AUTHENTICATION_OPTION_AD_PASSWORD_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_AUTHENTICATION + L10N_POSTFIX_OPTION + ".ActiveDirectoryPassword" + L10N_POSTFIX_LABEL;
    String L10N_AUTHENTICATION_OPTION_AD_INTEGRATED_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_AUTHENTICATION + L10N_POSTFIX_OPTION + ".ActiveDirectoryIntegrated" + L10N_POSTFIX_LABEL;

    // Option label constants for Response Buffering
    String L10N_RESPONSE_BUFFERING_OPTION_ADAPTIVE_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_RESPONSE_BUFFERING + L10N_POSTFIX_OPTION + ".adaptive" + L10N_POSTFIX_LABEL;
    String L10N_RESPONSE_BUFFERING_OPTION_FULL_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_RESPONSE_BUFFERING + L10N_POSTFIX_OPTION + ".full" + L10N_POSTFIX_LABEL;

    // Option label constants for Select Method
    String L10N_SELECT_METHOD_OPTION_DIRECT_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SELECT_METHOD + L10N_POSTFIX_OPTION + ".direct" + L10N_POSTFIX_LABEL;
    String L10N_SELECT_METHOD_OPTION_CURSOR_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SELECT_METHOD + L10N_POSTFIX_OPTION + ".cursor" + L10N_POSTFIX_LABEL;

    // Option label constants for Application Intent
    String L10N_APPLICATION_INTENT_OPTION_READWRITE_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_APPLICATION_INTENT + L10N_POSTFIX_OPTION + ".ReadWrite" + L10N_POSTFIX_LABEL;
    String L10N_APPLICATION_INTENT_OPTION_READONLY_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_APPLICATION_INTENT + L10N_POSTFIX_OPTION + ".ReadOnly" + L10N_POSTFIX_LABEL;

    // Option label constants for Column Encryption
    String L10N_COLUMN_ENCRYPTION_OPTION_DISABLED_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_COLUMN_ENCRYPTION + L10N_POSTFIX_OPTION + ".Disabled" + L10N_POSTFIX_LABEL;
    String L10N_COLUMN_ENCRYPTION_OPTION_ENABLED_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_COLUMN_ENCRYPTION + L10N_POSTFIX_OPTION + ".Enabled" + L10N_POSTFIX_LABEL;
    String L10N_COLUMN_ENCRYPTION_OPTION_RESULTSETONLY_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_COLUMN_ENCRYPTION + L10N_POSTFIX_OPTION + ".ResultSetOnly" + L10N_POSTFIX_LABEL;

    // Default value constants
    String DEFAULT_PASSWORD = "";
    String DEFAULT_USER = "";
    String DEFAULT_APPLICATION_NAME = "";
    int DEFAULT_PORT_NUMBER = 1433;
    String DEFAULT_INSTANCE_NAME = "";
    String DEFAULT_SERVER_NAME = "localhost";
    String DEFAULT_DATABASE_NAME = "";
    String DEFAULT_ENCRYPT = "true";
    boolean DEFAULT_TRUST_SERVER_CERTIFICATE = false;
    boolean DEFAULT_INTEGRATED_SECURITY = false;
    String DEFAULT_AUTHENTICATION = "NotSpecified";
    int DEFAULT_LOGIN_TIMEOUT = 30;
    int DEFAULT_QUERY_TIMEOUT = -1;
    int DEFAULT_SOCKET_TIMEOUT = 0;
    String DEFAULT_RESPONSE_BUFFERING = "adaptive";
    String DEFAULT_SELECT_METHOD = "direct";
    String DEFAULT_APPLICATION_INTENT = "readwrite";
    boolean DEFAULT_MULTI_SUBNET_FAILOVER = false;
    String DEFAULT_FAILOVER_PARTNER = "";
    int DEFAULT_PACKET_SIZE = 4096;
    int DEFAULT_LOCK_TIMEOUT = -1;
    String DEFAULT_COLUMN_ENCRYPTION_SETTING = "Disabled";
    boolean DEFAULT_SEND_STRING_PARAMETERS_AS_UNICODE = true;

    @AttributeDefinition(name = L10N_PASSWORD_NAME, description = L10N_PASSWORD_DESCRIPTION, type = AttributeType.PASSWORD, defaultValue = DEFAULT_PASSWORD)
    default String _password() {
        return DEFAULT_PASSWORD;
    }

    @AttributeDefinition(name = L10N_USER_NAME, description = L10N_USER_DESCRIPTION, defaultValue = DEFAULT_USER)
    default String user() {
        return DEFAULT_USER;
    }

    @AttributeDefinition(name = L10N_APPLICATIONNAME_NAME, description = L10N_APPLICATIONNAME_DESCRIPTION, defaultValue = DEFAULT_APPLICATION_NAME)
    default String applicationName() {
        return DEFAULT_APPLICATION_NAME;
    }

    @AttributeDefinition(name = L10N_PORTNUMBER_NAME, description = L10N_PORT_DESCRIPTION, defaultValue = DEFAULT_PORT_NUMBER
            + "")
    default int portNumber() {
        return DEFAULT_PORT_NUMBER;
    }

    @AttributeDefinition(name = L10N_INSTANCENAME_NAME, description = L10N_INSTANCENAME_DESCRIPTION, defaultValue = DEFAULT_INSTANCE_NAME)
    default String instanceName() {
        return DEFAULT_INSTANCE_NAME;
    }

    @AttributeDefinition(name = L10N_SERVERNAME_NAME, description = L10N_SERVERNAME_DESCRIPTION, defaultValue = DEFAULT_SERVER_NAME)
    default String serverName() {
        return DEFAULT_SERVER_NAME;
    }

    @AttributeDefinition(name = L10N_DATABASENAME_NAME, description = L10N_DATABASENAME_DESCRIPTION, defaultValue = DEFAULT_DATABASE_NAME)
    default String databaseName() {
        return DEFAULT_DATABASE_NAME;
    }

    @AttributeDefinition(name = L10N_ENCRYPT_NAME, description = L10N_ENCRYPT_DESCRIPTION, defaultValue = DEFAULT_ENCRYPT, options = {
            @Option(label = L10N_ENCRYPT_OPTION_TRUE_LABEL, value = "true"),
            @Option(label = L10N_ENCRYPT_OPTION_FALSE_LABEL, value = "false"),
            @Option(label = L10N_ENCRYPT_OPTION_STRICT_LABEL, value = "strict")
    })
    default String encrypt() {
        return DEFAULT_ENCRYPT;
    }

    @AttributeDefinition(name = L10N_TRUST_SERVER_CERTIFICATE_NAME, description = L10N_TRUST_SERVER_CERTIFICATE_DESCRIPTION, defaultValue = DEFAULT_TRUST_SERVER_CERTIFICATE
            + "")
    default boolean trustServerCertificate() {
        return DEFAULT_TRUST_SERVER_CERTIFICATE;
    }

    @AttributeDefinition(name = L10N_INTEGRATED_SECURITY_NAME, description = L10N_INTEGRATED_SECURITY_DESCRIPTION, defaultValue = DEFAULT_INTEGRATED_SECURITY
            + "")
    default boolean integratedSecurity() {
        return DEFAULT_INTEGRATED_SECURITY;
    }

    @AttributeDefinition(name = L10N_AUTHENTICATION_NAME, description = L10N_AUTHENTICATION_DESCRIPTION, defaultValue = DEFAULT_AUTHENTICATION, options = {
            @Option(label = L10N_AUTHENTICATION_OPTION_NOT_SPECIFIED_LABEL, value = "NotSpecified"),
            @Option(label = L10N_AUTHENTICATION_OPTION_SQL_PASSWORD_LABEL, value = "SqlPassword"),
            @Option(label = L10N_AUTHENTICATION_OPTION_AD_PASSWORD_LABEL, value = "ActiveDirectoryPassword"),
            @Option(label = L10N_AUTHENTICATION_OPTION_AD_INTEGRATED_LABEL, value = "ActiveDirectoryIntegrated")
    })
    default String authentication() {
        return DEFAULT_AUTHENTICATION;
    }

    @AttributeDefinition(name = L10N_LOGIN_TIMEOUT_NAME, description = L10N_LOGIN_TIMEOUT_DESCRIPTION, defaultValue = DEFAULT_LOGIN_TIMEOUT
            + "")
    default int loginTimeout() {
        return DEFAULT_LOGIN_TIMEOUT;
    }

    @AttributeDefinition(name = L10N_QUERY_TIMEOUT_NAME, description = L10N_QUERY_TIMEOUT_DESCRIPTION, defaultValue = DEFAULT_QUERY_TIMEOUT
            + "")
    default int queryTimeout() {
        return DEFAULT_QUERY_TIMEOUT;
    }

    @AttributeDefinition(name = L10N_SOCKET_TIMEOUT_NAME, description = L10N_SOCKET_TIMEOUT_DESCRIPTION, defaultValue = DEFAULT_SOCKET_TIMEOUT
            + "")
    default int socketTimeout() {
        return DEFAULT_SOCKET_TIMEOUT;
    }

    @AttributeDefinition(name = L10N_RESPONSE_BUFFERING_NAME, description = L10N_RESPONSE_BUFFERING_DESCRIPTION, defaultValue = DEFAULT_RESPONSE_BUFFERING, options = {
            @Option(label = L10N_RESPONSE_BUFFERING_OPTION_ADAPTIVE_LABEL, value = "adaptive"),
            @Option(label = L10N_RESPONSE_BUFFERING_OPTION_FULL_LABEL, value = "full")
    })
    default String responseBuffering() {
        return DEFAULT_RESPONSE_BUFFERING;
    }

    @AttributeDefinition(name = L10N_SELECT_METHOD_NAME, description = L10N_SELECT_METHOD_DESCRIPTION, defaultValue = DEFAULT_SELECT_METHOD, options = {
            @Option(label = L10N_SELECT_METHOD_OPTION_DIRECT_LABEL, value = "direct"),
            @Option(label = L10N_SELECT_METHOD_OPTION_CURSOR_LABEL, value = "cursor")
    })
    default String selectMethod() {
        return DEFAULT_SELECT_METHOD;
    }

    @AttributeDefinition(name = L10N_APPLICATION_INTENT_NAME, description = L10N_APPLICATION_INTENT_DESCRIPTION, defaultValue = DEFAULT_APPLICATION_INTENT, options = {
            @Option(label = L10N_APPLICATION_INTENT_OPTION_READWRITE_LABEL, value = "ReadWrite"),
            @Option(label = L10N_APPLICATION_INTENT_OPTION_READONLY_LABEL, value = "ReadOnly")
    })
    default String applicationIntent() {
        return DEFAULT_APPLICATION_INTENT;
    }

    @AttributeDefinition(name = L10N_MULTI_SUBNET_FAILOVER_NAME, description = L10N_MULTI_SUBNET_FAILOVER_DESCRIPTION, defaultValue = DEFAULT_MULTI_SUBNET_FAILOVER
            + "")
    default boolean multiSubnetFailover() {
        return DEFAULT_MULTI_SUBNET_FAILOVER;
    }

    @AttributeDefinition(name = L10N_FAILOVER_PARTNER_NAME, description = L10N_FAILOVER_PARTNER_DESCRIPTION, defaultValue = DEFAULT_FAILOVER_PARTNER)
    default String failoverPartner() {
        return DEFAULT_FAILOVER_PARTNER;
    }

    @AttributeDefinition(name = L10N_PACKET_SIZE_NAME, description = L10N_PACKET_SIZE_DESCRIPTION, defaultValue = DEFAULT_PACKET_SIZE
            + "")
    default int packetSize() {
        return DEFAULT_PACKET_SIZE;
    }

    @AttributeDefinition(name = L10N_LOCK_TIMEOUT_NAME, description = L10N_LOCK_TIMEOUT_DESCRIPTION, defaultValue = DEFAULT_LOCK_TIMEOUT
            + "")
    default int lockTimeout() {
        return DEFAULT_LOCK_TIMEOUT;
    }

    @AttributeDefinition(name = L10N_COLUMN_ENCRYPTION_NAME, description = L10N_COLUMN_ENCRYPTION_DESCRIPTION, defaultValue = DEFAULT_COLUMN_ENCRYPTION_SETTING, options = {
            @Option(label = L10N_COLUMN_ENCRYPTION_OPTION_DISABLED_LABEL, value = "Disabled"),
            @Option(label = L10N_COLUMN_ENCRYPTION_OPTION_ENABLED_LABEL, value = "Enabled"),
            @Option(label = L10N_COLUMN_ENCRYPTION_OPTION_RESULTSETONLY_LABEL, value = "ResultSetOnly")
    })
    default String columnEncryptionSetting() {
        return DEFAULT_COLUMN_ENCRYPTION_SETTING;
    }

    @AttributeDefinition(name = L10N_SEND_STRING_PARAMETERS_AS_UNICODE_NAME, description = L10N_SEND_STRING_PARAMETERS_AS_UNICODE_DESCRIPTION, defaultValue = DEFAULT_SEND_STRING_PARAMETERS_AS_UNICODE
            + "")
    default boolean sendStringParametersAsUnicode() {
        return DEFAULT_SEND_STRING_PARAMETERS_AS_UNICODE;
    }
}
