/*
* Copyright (c) 2024 Contributors to the Eclipse Foundation.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
*
* Contributors:
*   SmartCity Jena - initial
*   Stefan Bischof (bipolis.org) - initial
*/
package org.eclipse.daanse.jdbc.datasource.metatype.mysql.api.ocd;

import org.eclipse.daanse.jdbc.datasource.metatype.mysql.api.Constants;
import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.AttributeType;
import org.osgi.service.metatype.annotations.Option;

public interface BaseConfig {

    String OCD_LOCALIZATION = "OSGI-INF/l10n/org.eclipse.daanse.jdbc.datasource.metatype.mysql.ocd";
    String L10N_PREFIX = "%";

    String L10N_POSTFIX_DESCRIPTION = ".description";
    String L10N_POSTFIX_NAME = ".name";
    String L10N_POSTFIX_OPTION = ".option";
    String L10N_POSTFIX_LABEL = ".label";

    String L10N_HOST_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_HOST + L10N_POSTFIX_NAME;
    String L10N_HOST_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_HOST + L10N_POSTFIX_DESCRIPTION;

    String L10N_PORT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PORT + L10N_POSTFIX_NAME;
    String L10N_PORT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PORT + L10N_POSTFIX_DESCRIPTION;

    String L10N_DATABASENAME_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DATABASENAME + L10N_POSTFIX_NAME;
    String L10N_DATABASENAME_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DATABASENAME
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_PASSWORD_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PASSWORD + L10N_POSTFIX_NAME;
    String L10N_PASSWORD_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PASSWORD + L10N_POSTFIX_DESCRIPTION;

    String L10N_USER_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USER + L10N_POSTFIX_NAME;
    String L10N_USER_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USER + L10N_POSTFIX_DESCRIPTION;

    String L10N_AUTO_RECONNECT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_AUTO_RECONNECT + L10N_POSTFIX_NAME;
    String L10N_AUTO_RECONNECT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_AUTO_RECONNECT
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_CONNECTION_TIMEOUT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_CONNECTION_TIMEOUT
            + L10N_POSTFIX_NAME;
    String L10N_CONNECTION_TIMEOUT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_CONNECTION_TIMEOUT
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_SOCKET_TIMEOUT_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SOCKET_TIMEOUT + L10N_POSTFIX_NAME;
    String L10N_SOCKET_TIMEOUT_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SOCKET_TIMEOUT
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_USE_SSL_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USE_SSL + L10N_POSTFIX_NAME;
    String L10N_USE_SSL_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USE_SSL + L10N_POSTFIX_DESCRIPTION;

    String L10N_CHARACTER_ENCODING_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_CHARACTER_ENCODING
            + L10N_POSTFIX_NAME;
    String L10N_CHARACTER_ENCODING_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_CHARACTER_ENCODING
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_USE_SERVER_PREPARED_STMTS_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USE_SERVER_PREPARED_STMTS
            + L10N_POSTFIX_NAME;
    String L10N_USE_SERVER_PREPARED_STMTS_DESCRIPTION = L10N_PREFIX
            + Constants.DATASOURCE_PROPERTY_USE_SERVER_PREPARED_STMTS + L10N_POSTFIX_DESCRIPTION;

    String L10N_CACHE_PREPARED_STMTS_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_CACHE_PREPARED_STMTS
            + L10N_POSTFIX_NAME;
    String L10N_CACHE_PREPARED_STMTS_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_CACHE_PREPARED_STMTS
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_PREPARED_STATEMENT_CACHE_SIZE_NAME = L10N_PREFIX
            + Constants.DATASOURCE_PROPERTY_PREPARED_STATEMENT_CACHE_SIZE + L10N_POSTFIX_NAME;
    String L10N_PREPARED_STATEMENT_CACHE_SIZE_DESCRIPTION = L10N_PREFIX
            + Constants.DATASOURCE_PROPERTY_PREPARED_STATEMENT_CACHE_SIZE + L10N_POSTFIX_DESCRIPTION;

    String L10N_USE_COMPRESSION_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USE_COMPRESSION + L10N_POSTFIX_NAME;
    String L10N_USE_COMPRESSION_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USE_COMPRESSION
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_ZERO_DATETIME_BEHAVIOR_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ZERO_DATETIME_BEHAVIOR
            + L10N_POSTFIX_NAME;
    String L10N_ZERO_DATETIME_BEHAVIOR_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ZERO_DATETIME_BEHAVIOR
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_SERVER_TIMEZONE_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SERVER_TIMEZONE + L10N_POSTFIX_NAME;
    String L10N_SERVER_TIMEZONE_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_SERVER_TIMEZONE
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_USE_AFFECTED_ROWS_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USE_AFFECTED_ROWS
            + L10N_POSTFIX_NAME;
    String L10N_USE_AFFECTED_ROWS_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USE_AFFECTED_ROWS
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_ALLOW_MULTI_QUERIES_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ALLOW_MULTI_QUERIES
            + L10N_POSTFIX_NAME;
    String L10N_ALLOW_MULTI_QUERIES_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ALLOW_MULTI_QUERIES
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_REWRITE_BATCHED_STATEMENTS_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_REWRITE_BATCHED_STATEMENTS
            + L10N_POSTFIX_NAME;
    String L10N_REWRITE_BATCHED_STATEMENTS_DESCRIPTION = L10N_PREFIX
            + Constants.DATASOURCE_PROPERTY_REWRITE_BATCHED_STATEMENTS + L10N_POSTFIX_DESCRIPTION;

    String L10N_USE_INFORMATION_SCHEMA_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USE_INFORMATION_SCHEMA
            + L10N_POSTFIX_NAME;
    String L10N_USE_INFORMATION_SCHEMA_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USE_INFORMATION_SCHEMA
            + L10N_POSTFIX_DESCRIPTION;

    String L10N_LOGGER_CLASS_NAME_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_LOGGER_CLASS_NAME
            + L10N_POSTFIX_NAME;
    String L10N_LOGGER_CLASS_NAME_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_LOGGER_CLASS_NAME
            + L10N_POSTFIX_DESCRIPTION;

    // Option label constants following .option.optionname.label pattern
    String L10N_ZERO_DATETIME_BEHAVIOR_OPTION_EXCEPTION_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ZERO_DATETIME_BEHAVIOR + L10N_POSTFIX_OPTION + ".exception" + L10N_POSTFIX_LABEL;
    String L10N_ZERO_DATETIME_BEHAVIOR_OPTION_CONVERTTONULL_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ZERO_DATETIME_BEHAVIOR + L10N_POSTFIX_OPTION + ".converttonull" + L10N_POSTFIX_LABEL;
    String L10N_ZERO_DATETIME_BEHAVIOR_OPTION_ROUND_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_ZERO_DATETIME_BEHAVIOR + L10N_POSTFIX_OPTION + ".round" + L10N_POSTFIX_LABEL;

    // Default value constants
    String DEFAULT_PASSWORD = "";
    String DEFAULT_USER = "";
    String DEFAULT_DATABASENAME = "";
    int DEFAULT_PORT = 3306;
    String DEFAULT_HOST = "localhost";
    boolean DEFAULT_AUTO_RECONNECT = false;
    int DEFAULT_CONNECT_TIMEOUT = 0;
    int DEFAULT_SOCKET_TIMEOUT = 0;
    boolean DEFAULT_USE_SSL = true;
    String DEFAULT_CHARACTER_ENCODING = "UTF-8";
    boolean DEFAULT_USE_SERVER_PREPARED_STMTS = false;
    boolean DEFAULT_CACHE_PREPARED_STMTS = false;
    int DEFAULT_PREPARED_STATEMENT_CACHE_SIZE = 25;
    boolean DEFAULT_USE_COMPRESSION = false;
    String DEFAULT_ZERO_DATETIME_BEHAVIOR = "exception";
    String DEFAULT_SERVER_TIMEZONE = "";
    boolean DEFAULT_USE_AFFECTED_ROWS = false;
    boolean DEFAULT_ALLOW_MULTI_QUERIES = false;
    boolean DEFAULT_REWRITE_BATCHED_STATEMENTS = false;
    boolean DEFAULT_USE_INFORMATION_SCHEMA = true;
    String DEFAULT_LOGGER_CLASS_NAME = "";

    @AttributeDefinition(name = L10N_PASSWORD_NAME, description = L10N_PASSWORD_DESCRIPTION, type = AttributeType.PASSWORD, defaultValue = DEFAULT_PASSWORD)
    default String _password() {
        return DEFAULT_PASSWORD;
    }

    @AttributeDefinition(name = L10N_USER_NAME, description = L10N_USER_DESCRIPTION, defaultValue = DEFAULT_USER)
    default String user() {
        return DEFAULT_USER;
    }

    @AttributeDefinition(name = L10N_DATABASENAME_NAME, description = L10N_DATABASENAME_DESCRIPTION, defaultValue = DEFAULT_DATABASENAME)
    default String databaseName() {
        return DEFAULT_DATABASENAME;
    }

    @AttributeDefinition(name = L10N_PORT_NAME, description = L10N_PORT_DESCRIPTION, required = true, defaultValue = DEFAULT_PORT
            + "")
    default int port() {
        return DEFAULT_PORT;
    }

    @AttributeDefinition(name = L10N_HOST_NAME, description = L10N_HOST_DESCRIPTION, required = true, defaultValue = DEFAULT_HOST)
    default String host() {
        return DEFAULT_HOST;
    }

    @AttributeDefinition(name = L10N_AUTO_RECONNECT_NAME, description = L10N_AUTO_RECONNECT_DESCRIPTION, defaultValue = DEFAULT_AUTO_RECONNECT
            + "")
    default boolean autoReconnect() {
        return DEFAULT_AUTO_RECONNECT;
    }

    @AttributeDefinition(name = L10N_CONNECTION_TIMEOUT_NAME, description = L10N_CONNECTION_TIMEOUT_DESCRIPTION, defaultValue = DEFAULT_CONNECT_TIMEOUT
            + "")
    default int connectTimeout() {
        return DEFAULT_CONNECT_TIMEOUT;
    }

    @AttributeDefinition(name = L10N_SOCKET_TIMEOUT_NAME, description = L10N_SOCKET_TIMEOUT_DESCRIPTION, defaultValue = DEFAULT_SOCKET_TIMEOUT
            + "")
    default int socketTimeout() {
        return DEFAULT_SOCKET_TIMEOUT;
    }

    @AttributeDefinition(name = L10N_USE_SSL_NAME, description = L10N_USE_SSL_DESCRIPTION, defaultValue = DEFAULT_USE_SSL
            + "")
    default boolean useSSL() {
        return DEFAULT_USE_SSL;
    }

    @AttributeDefinition(name = L10N_CHARACTER_ENCODING_NAME, description = L10N_CHARACTER_ENCODING_DESCRIPTION, defaultValue = DEFAULT_CHARACTER_ENCODING)
    default String characterEncoding() {
        return DEFAULT_CHARACTER_ENCODING;
    }

    @AttributeDefinition(name = L10N_USE_SERVER_PREPARED_STMTS_NAME, description = L10N_USE_SERVER_PREPARED_STMTS_DESCRIPTION, defaultValue = DEFAULT_USE_SERVER_PREPARED_STMTS
            + "")
    default boolean useServerPrepStmts() {
        return DEFAULT_USE_SERVER_PREPARED_STMTS;
    }

    @AttributeDefinition(name = L10N_CACHE_PREPARED_STMTS_NAME, description = L10N_CACHE_PREPARED_STMTS_DESCRIPTION, defaultValue = DEFAULT_CACHE_PREPARED_STMTS
            + "")
    default boolean cachePrepStmts() {
        return DEFAULT_CACHE_PREPARED_STMTS;
    }

    @AttributeDefinition(name = L10N_PREPARED_STATEMENT_CACHE_SIZE_NAME, description = L10N_PREPARED_STATEMENT_CACHE_SIZE_DESCRIPTION, defaultValue = DEFAULT_PREPARED_STATEMENT_CACHE_SIZE
            + "")
    default int prepStmtCacheSize() {
        return DEFAULT_PREPARED_STATEMENT_CACHE_SIZE;
    }

    @AttributeDefinition(name = L10N_USE_COMPRESSION_NAME, description = L10N_USE_COMPRESSION_DESCRIPTION, defaultValue = DEFAULT_USE_COMPRESSION
            + "")
    default boolean useCompression() {
        return DEFAULT_USE_COMPRESSION;
    }

    @AttributeDefinition(name = L10N_ZERO_DATETIME_BEHAVIOR_NAME, description = L10N_ZERO_DATETIME_BEHAVIOR_DESCRIPTION, defaultValue = DEFAULT_ZERO_DATETIME_BEHAVIOR, options = {
            @Option(label = L10N_ZERO_DATETIME_BEHAVIOR_OPTION_EXCEPTION_LABEL, value = "exception"),
            @Option(label = L10N_ZERO_DATETIME_BEHAVIOR_OPTION_CONVERTTONULL_LABEL, value = "convertToNull"),
            @Option(label = L10N_ZERO_DATETIME_BEHAVIOR_OPTION_ROUND_LABEL, value = "round")
    })
    default String zeroDateTimeBehavior() {
        return DEFAULT_ZERO_DATETIME_BEHAVIOR;
    }

    @AttributeDefinition(name = L10N_SERVER_TIMEZONE_NAME, description = L10N_SERVER_TIMEZONE_DESCRIPTION, defaultValue = DEFAULT_SERVER_TIMEZONE)
    default String serverTimezone() {
        return DEFAULT_SERVER_TIMEZONE;
    }

    @AttributeDefinition(name = L10N_USE_AFFECTED_ROWS_NAME, description = L10N_USE_AFFECTED_ROWS_DESCRIPTION, defaultValue = DEFAULT_USE_AFFECTED_ROWS
            + "")
    default boolean useAffectedRows() {
        return DEFAULT_USE_AFFECTED_ROWS;
    }

    @AttributeDefinition(name = L10N_ALLOW_MULTI_QUERIES_NAME, description = L10N_ALLOW_MULTI_QUERIES_DESCRIPTION, defaultValue = DEFAULT_ALLOW_MULTI_QUERIES
            + "")
    default boolean allowMultiQueries() {
        return DEFAULT_ALLOW_MULTI_QUERIES;
    }

    @AttributeDefinition(name = L10N_REWRITE_BATCHED_STATEMENTS_NAME, description = L10N_REWRITE_BATCHED_STATEMENTS_DESCRIPTION, defaultValue = DEFAULT_REWRITE_BATCHED_STATEMENTS
            + "")
    default boolean rewriteBatchedStatements() {
        return DEFAULT_REWRITE_BATCHED_STATEMENTS;
    }

    @AttributeDefinition(name = L10N_USE_INFORMATION_SCHEMA_NAME, description = L10N_USE_INFORMATION_SCHEMA_DESCRIPTION, defaultValue = DEFAULT_USE_INFORMATION_SCHEMA
            + "")
    default boolean useInformationSchema() {
        return DEFAULT_USE_INFORMATION_SCHEMA;
    }

    @AttributeDefinition(name = L10N_LOGGER_CLASS_NAME_NAME, description = L10N_LOGGER_CLASS_NAME_DESCRIPTION, defaultValue = DEFAULT_LOGGER_CLASS_NAME)
    default String logger() {
        return DEFAULT_LOGGER_CLASS_NAME;
    }
}
