/*
* Copyright (c) 2024 Contributors to the Eclipse Foundation.
*
* This program and the accompanying materials are made
* available under the terms of the Eclipse Public License 2.0
* which is available at https://www.eclipse.org/legal/epl-2.0/
*
* SPDX-License-Identifier: EPL-2.0
*
* Contributors:
*   SmartCity Jena - initial
*   Stefan Bischof (bipolis.org) - initial
*/
package org.eclipse.daanse.jdbc.datasource.h2.api.ocd;

import org.eclipse.daanse.jdbc.datasource.h2.api.Constants;
import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.AttributeType;
import org.osgi.service.metatype.annotations.Option;

public interface BaseConfig {

    String OCD_LOCALIZATION = "OSGI-INF/l10n/org.eclipse.daanse.jdbc.datasource.h2.ocd";
    String L10N_PREFIX = "%";
    String L10N_POSTFIX_DESCRIPTION = ".description";
    String L10N_POSTFIX_NAME = ".name";
    String L10N_POSTFIX_OPTION = ".option";
    String L10N_POSTFIX_LABEL = ".label";

    String L10N_DEBUG_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DEBUG + L10N_POSTFIX_NAME;
    String L10N_DEBUG_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DEBUG + L10N_POSTFIX_DESCRIPTION;

    String L10N_DESCRIPTION_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DESCRIPTION + L10N_POSTFIX_NAME;
    String L10N_DESCRIPTION_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DESCRIPTION + L10N_POSTFIX_DESCRIPTION;

    String L10N_PLUGABLE_FILESYSTEM_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_NAME;
    String L10N_PLUGABLE_FILESYSTEM_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_DESCRIPTION;

    String L10N_IDENTIFIER_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_IDENTIFIER + L10N_POSTFIX_NAME;
    String L10N_IDENTIFIER_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_IDENTIFIER + L10N_POSTFIX_DESCRIPTION;

    String L10N_PASSWORD_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PASSWORD + L10N_POSTFIX_NAME;
    String L10N_PASSWORD_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PASSWORD + L10N_POSTFIX_DESCRIPTION;

    String L10N_USERNAME_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USERNAME + L10N_POSTFIX_NAME;
    String L10N_USERNAME_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_USERNAME + L10N_POSTFIX_DESCRIPTION;

    String L10N_DATABASE_TO_UPPER_NAME = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DATABASE_TO_UPPER + L10N_POSTFIX_NAME;
    String L10N_DATABASE_TO_UPPER_DESCRIPTION = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_DATABASE_TO_UPPER + L10N_POSTFIX_DESCRIPTION;

    // Option label constants following .option.optionname.label pattern
    String L10N_PLUGABLE_FILESYSTEM_OPTION_ASYNC_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_OPTION + ".async" + L10N_POSTFIX_LABEL;
    String L10N_PLUGABLE_FILESYSTEM_OPTION_FILE_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_OPTION + ".file" + L10N_POSTFIX_LABEL;
    String L10N_PLUGABLE_FILESYSTEM_OPTION_MEMFS_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_OPTION + ".memfs" + L10N_POSTFIX_LABEL;
    String L10N_PLUGABLE_FILESYSTEM_OPTION_MEMLZF_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_OPTION + ".memlzf" + L10N_POSTFIX_LABEL;
    String L10N_PLUGABLE_FILESYSTEM_OPTION_NIOMAPPED_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_OPTION + ".niomapped" + L10N_POSTFIX_LABEL;
    String L10N_PLUGABLE_FILESYSTEM_OPTION_NIOMEMFS_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_OPTION + ".niomemfs" + L10N_POSTFIX_LABEL;
    String L10N_PLUGABLE_FILESYSTEM_OPTION_NIOMEMLZF_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_OPTION + ".niomemlzf" + L10N_POSTFIX_LABEL;
    String L10N_PLUGABLE_FILESYSTEM_OPTION_ZIP_LABEL = L10N_PREFIX + Constants.DATASOURCE_PROPERTY_PLUGABLE_FILESYSTEM + L10N_POSTFIX_OPTION + ".zip" + L10N_POSTFIX_LABEL;

    // Default value constants
    boolean DEFAULT_DEBUG = false;
    String DEFAULT_DESCRIPTION = "";
    String DEFAULT_PLUGABLE_FILESYSTEM = Constants.OPTION_PLUGABLE_FILESYSTEM_FILE;
    String DEFAULT_IDENTIFIER = "";
    String DEFAULT_PASSWORD = "";
    String DEFAULT_USERNAME = "";
    boolean DEFAULT_DATABASE_TO_UPPER = true;

    @AttributeDefinition(name = L10N_DEBUG_NAME, description = L10N_DEBUG_DESCRIPTION, defaultValue = DEFAULT_DEBUG + "")
    default boolean debug() {
        return DEFAULT_DEBUG;
    }

    @AttributeDefinition(name = L10N_DESCRIPTION_NAME, description = L10N_DESCRIPTION_DESCRIPTION, defaultValue = DEFAULT_DESCRIPTION)
    default String description() {
        return DEFAULT_DESCRIPTION;
    }

    @AttributeDefinition(name = L10N_PLUGABLE_FILESYSTEM_NAME, description = L10N_PLUGABLE_FILESYSTEM_DESCRIPTION, defaultValue = DEFAULT_PLUGABLE_FILESYSTEM, options = {
            @Option(label = L10N_PLUGABLE_FILESYSTEM_OPTION_ASYNC_LABEL, value = Constants.OPTION_PLUGABLE_FILESYSTEM_ASYNC),
            @Option(label = L10N_PLUGABLE_FILESYSTEM_OPTION_FILE_LABEL, value = Constants.OPTION_PLUGABLE_FILESYSTEM_FILE),
            @Option(label = L10N_PLUGABLE_FILESYSTEM_OPTION_MEMFS_LABEL, value = Constants.OPTION_PLUGABLE_FILESYSTEM_MEM_FS),
            @Option(label = L10N_PLUGABLE_FILESYSTEM_OPTION_MEMLZF_LABEL, value = Constants.OPTION_PLUGABLE_FILESYSTEM_MEM_LZF),
            @Option(label = L10N_PLUGABLE_FILESYSTEM_OPTION_NIOMAPPED_LABEL, value = Constants.OPTION_PLUGABLE_FILESYSTEM_NIO_MAPPED),
            @Option(label = L10N_PLUGABLE_FILESYSTEM_OPTION_NIOMEMFS_LABEL, value = Constants.OPTION_PLUGABLE_FILESYSTEM_NIO_MEM_FS),
            @Option(label = L10N_PLUGABLE_FILESYSTEM_OPTION_NIOMEMLZF_LABEL, value = Constants.OPTION_PLUGABLE_FILESYSTEM_NIO_MEM_LZF),
            @Option(label = L10N_PLUGABLE_FILESYSTEM_OPTION_ZIP_LABEL, value = Constants.OPTION_PLUGABLE_FILESYSTEM_ZIP) })
    default String plugableFilesystem() {
        return DEFAULT_PLUGABLE_FILESYSTEM;
    }

    @AttributeDefinition(name = L10N_IDENTIFIER_NAME, description = L10N_IDENTIFIER_DESCRIPTION, required = true, defaultValue = DEFAULT_IDENTIFIER)
    default String identifier() {
        return DEFAULT_IDENTIFIER;
    }

    @AttributeDefinition(name = L10N_PASSWORD_NAME, description = L10N_PASSWORD_DESCRIPTION, type = AttributeType.PASSWORD, defaultValue = DEFAULT_PASSWORD)
    default String _password() {
        return DEFAULT_PASSWORD;
    }

    @AttributeDefinition(name = L10N_USERNAME_NAME, description = L10N_USERNAME_DESCRIPTION, defaultValue = DEFAULT_USERNAME)
    default String username() {
        return DEFAULT_USERNAME;
    }

    @AttributeDefinition(name = L10N_DATABASE_TO_UPPER_NAME, description = L10N_DATABASE_TO_UPPER_DESCRIPTION, defaultValue = DEFAULT_DATABASE_TO_UPPER + "")
    default boolean databaseToUpper() {
        return DEFAULT_DATABASE_TO_UPPER;
    }
}
